### PR TITLE
test: Adding tests for the Register component

### PR DESCRIPTION
**Pull request by capellini**
As discussed in https://github.com/roerohan/8086.js/issues/19#issuecomment-698832367, adding tests for the Register component, which can be run by running the `npm test` command.

### CODE REVIEW

**Comment by roerohan** [comment]
@thebongy could you please review and merge this PR?

**Review by thebongy — APPROVED** [review]
lgtm, great work @capellini 

feel free to merge this @roerohan

**Comment by roerohan** [comment]
Great! Thanks again @capellini :100:

**Comment by capellini** [comment]
You're most welcome @roerohan.  Let me know if you'd like me to write more tests.

**Pull request merged**
